#  Key Strokes in Jupyter (Shortcuts)


    -to add a new cell -> alt + enter
    -to execute/run a cell -> ctrl + enter
    -to delete a cell -> esc, then d, d

    -to copy a group of cells and paste in another cell ->
        -> go to the particular cell
        -> Esc
        -> shift + use upward or downward arrow keys to select the number of cells
        -> ctrl + c to copy
        -> go to a new cell
        -> ctrl + v to paste
    
     - Cell Notations ->
         - Markdown - allows us to write comments about code without using "#"
         - code - allows us to write code and run the code
         - rawnbconvert - allows to convert the notebook to another format like html etc
      
     - to create whitespace between 1 cell and another cell
        - change the characteristic of the cell to Markdown        
        - enter 3 dashes in the cell and press alt + enter

# Basic Python - Data types and Variables


    - Variables are objects that hold a value
    eg - var1 = 100 --> 100 is assigned to the variable "var1"
    internally what  happens var1 is assigned an address in the memory
    and the value of 100 is assigned to var1

    - Rules in Python for variable names:
    *   Names can not start with a number.
    *   There can be no spaces in the name, use _ instead.
        WRONG - VAR 1 RIGHT - VAR_1
    *   Can't use any of these symbols :'",<>/?|()!@#$%^&*~-+
    *   It's considered best practice (PEP8) that
        names are lowercase.
        Avoid using the characters 'l' (lowercase letter el),
        'O' (uppercase letter oh), or
        'I' (uppercase letter eye) as single character variable names.
    *   Avoid using words that have special meaning in Python like "list" and "str"

In [ ]:
var1 = 2 # int type
var2 = 'Learning is fun' #string type
var3 = 2.3 #float type
var4 = '23' #string type
var5 = True #boolean type

In [ ]:
print(type(var1))
print(type(var2))
print(type(var3))
print(type(var4))
print(type(var5))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'str'>
<class 'bool'>

In [ ]:
### let's create an object called myvar0 and assign number 5 to it
myvar0 = 5
print(myvar0)

5

In [ ]:
myVar02=3000

print(myVar02)
print(myvar02)  ### case sensitive..hence error

3000

NameError: name 'myvar02' is not defined

In [ ]:
# different memory address to different values
a = 12
print(id(a))

a = 21
print(id(a))

b = 12
print(id(b))

137725889167952
137725889168240
137725889167952

In [ ]:
# input from user end without any specific datatype
print(input("Enter your name here: "))

Enter your name here: Sapna
Sapna

In [ ]:
# Input with specific datatype stored in a variable then use it
a = int(input("enter a number: "))
print(a)

enter a number: 44
44

In [ ]:
b,c = input().split()
print(b,c)

444 112
444 112

In [ ]:
num1 , num2 = input("enter 2 numbers ").split()
print(num1, num2)

enter the num23 34
23 34



### jupyter trick
     - type half of the word "my" and press "TAB" key. we will see list of words that start with word "my".
     - if we want to know what a particular function does. we can call python help in jupyter by -> shift + tab key

### Concept of Dynamic Typing in Python
    - type of the variable will change based on the value assigned to the variable.
    - very powerful, but can be abused if the programmer does not take enough precautions.

In [ ]:
my_new_var0 = 100
type(my_new_var0)

int

In [ ]:
my_new_var0 = 'this is a string'
type(my_new_var0)

str

### Re assignment of variables
  - concept of operating with a variable and assigning the output of operation to the same variable

In [ ]:
my_var3 = 'this is a string'
my_var4 = "i am also a string"
print(my_var3)
print(my_var4)
print(type(my_var3))
print(type(my_var4))

this is a string
i am also a string
<class 'str'>
<class 'str'>

In [ ]:
# python follows "dynamic typing" - based on the data assigned, the type of the variable can change
my_var4 = 10000
print(my_var4)
print(type(my_var4))

10000
<class 'int'>

In [ ]:
#Numerical Literal
a=0b1010 #binary Literal
b=100 #Decimal Literal
c= 0o310 #Octal Literal
d= 0x12c
print(a,b,c,d)

10 100 200 300
1.2 120.0 0.0012
3.14j
Go Green
raw \n string
🐍
5
4
None

In [ ]:
#Float Literal
x=1.2
y=1.2e2 #e2 10x10
z=1.2e-3
print(x,y,z)

In [ ]:
#Complex Literal
l=3.14j
print(l)

In [ ]:
#String Literals
S="Go Green"
raw_str=r"raw \n string"
f=u"\U0001F40D"
print(S)
print(raw_str)
print(f)

In [ ]:
#Boolean Literals
m= True + 4
n= False + 4
print(m)
print(n)

5
4

In [ ]:
#Special Literal
o=None
print(o)

#  Operators
The operator can be defined as a symbol which is responsible for a particular operation between two operands. Operators are the pillars of a program on which the logic is built in a specific programming language. Python provides a variety of operators, which are described as follows.

- Arithmetic operators
- Assignment Operators
- Relational operators
- Logical Operators
- Bitwise Operators

## Arithmetic

Basic Arithmetic In Python
-  Numbers in Python - INTEGERS (both +ve and -ve numbers), Floating point number (decimal numbers)
-  Basic Arithmetic Operations

In [ ]:
### variable addition/subtraction/multiplication/division/powers
my_var1 = 100
my_var0 = 5

print(my_var0 + my_var1)
print(my_var1+my_var1)
print(my_var1-my_var0)
print(my_var1*my_var0)
print(my_var0/my_var1)
print(my_var1**my_var0)
print(my_var0//my_var1)

105
200
95
500
0.05
10000000000
0

In [ ]:
## TO PRINT
print("this is arithmetic add")
print(1+2)
print(3+4)
### the output of 3+4 overrides the output of 1+2

### subraction
print(100-20)

#Override
print(-100-20)

###multiplication
print(100*20)

#Override
print(-100.30  * 21.55)

#division
print(300/20)
print(3/2)
print(-200/19)
print(-100/-10)

this is arithmetic add
3
7
80
-120
2000
-2161.465
15.0
1.5
-10.526315789473685
10.0

In [ ]:
### floor division ### quotient
### the // operator it truncates the decimal without rounding and returns only the integer result
print(7.0//4)

### Module
print(7.0 % 4)

### powers
print(2**3)

print(2**-3)

1.0
3.0
8
0.125

### BODMAS (Bracket, Off, Division, Multiplication, Addition, Subtraction)

In [ ]:
print(2 + 10 * 10 + 3)

105

In [ ]:
print((2+10) * (10+3))

156

In [ ]:
print((0.1+0.2)-(0.3))

### ideally we should get a zero.
### python and our computers follows what is called as "floating point accuracy"
### even though for the naked eye, the answer is zero , python returns a number which extremely closer to zero,
#### but not exactly zero
#### 5.551115123125783e-17 can be translated as = 1/5.551115123125783 e**17

5.551115123125783e-17

In [ ]:
print(0.2-0.2)
print((0.2+0.1) - 0.3)
print(0.1+0.2)
print(0.1)
print(0.2)
print(0.3 )
print(0.1-0.2)
print(0.2-0.1)
print(0.2-0.3)
print(0.3-0.2)
print(0.3-0.1)
print(0.1-0.3)

0.0
5.551115123125783e-17
0.30000000000000004
0.1
0.2
0.3
-0.1
0.1
-0.09999999999999998
0.09999999999999998
0.19999999999999998
-0.19999999999999998

## Assignment Operator

= It assigns value of right side of expression to left side operand

Combined operators:- +=, -=, *=, /=, %=, //=, **=

In [ ]:
var1 = 21
var2 = 'String Value'
var3 = '21'

In [ ]:
# Multiple assignment
a, b, c = 5, 6, 7
print(a)
print(b)
print(c)

# Multiple assignment
x = y = z = 99
print(x)
print(y)
print(z)

5
6
7
99
99
99

In [ ]:
var1 = 2
print(var1, 'before executing')
var1 +=2
print(var1, 'after executing +=')
var1 -=1
print(var1, 'after executing -=')

2 before executing
4 after executing +=
3 after executing -=

## Relational Operator

*   '<' Less than
*   '>' Greater than
*   '==' Equal to
*   '!=' Not equal to
*   '>=' Greater than or equal to
*   '<=' Less than or equal to

In [ ]:
4<5

True

In [ ]:
var1 = 10
var2 = 20
var2>var1

True

In [ ]:
var1 = 10
var2 = 20
var2==var1

False

In [ ]:
var1 = 10
var2 = 20
var2<=var1

False

## Logical Operator

- Logical AND: True if both the operands are true	x and y
- Logical OR: True if either of the operands is true	x or y
- 	Logical NOT: True if operand is false

In [ ]:
var1 = 10
var2 = 20
print(var2>=var1 or var2>var1)

True

In [ ]:
var1 = 10
var2 = 10
print(var2>=var1 and var2>var1)

False

In [ ]:
var = 0
var1 = 10
not var1

False

In [ ]:
var = 0
var1 = 1
if not var:
    print("True")

True

In [ ]:
# Python program which attempts to
# overload ~ operator as binary operator


class A:
	def __init__(self, a):
		self.a = a

	# Overloading ~ operator, but with two operands
	def __invert__(self):
		return "This is the ~ operator, overloaded as binary operator."


ob1 = A(2)

print(~ob1)

This is the ~ operator, overloaded as binary operator.

#  Strings in Python

In [ ]:
'hello'
print('hello')
print("hello i am a string")

print("hello, i am Kevin O'Spacey")

### use of double quotes is imperative when we have strings with characters like apostrophe

mystr1= "12305"
print(mystr1)
print(type(mystr1))

hello
hello i am a string
hello, i am Kevin O'Spacey
12305
<class 'str'>

### STRING INDEXING AND SLICING
- If we want to find specific characters in the string or do operations with every or all character in a string, indexing is used
index in python starts at 0
-  slicing captures a slice of a string
- Format of slicing - stringname[start:stop:step]
  - start - index from where the slicing should start
  - stop  - the index we will go up to but does not include
  - step  - is the size of "jump" we take while slicing

In [ ]:
mystr2 = 'abcdestring'
len(mystr2)

11

In [ ]:
### grab the portion of string representing "cde"
print(mystr2[2:5])

cde

In [ ]:
### to grab - cdestring
print(mystr2[2:11])
print(mystr2[2:])

cdestring
cdestring

In [ ]:
### step example  - abcdestring
print(mystr2[0:11:1])

abcdestring

## Built in Functions in Strings
- len()
- lower()
- upper()
- split()
- count() and many more

In [ ]:
### length of a string
mystr3 = "gjfdgfgg jfddkfl"
print(mystr3)
print(len(mystr3))

### to convert a string from lower case to upper case
print(mystr3.upper())

gjfdgfgg jfddkfl
16
GJFDGFGG JFDDKFL

In [ ]:
### convert to lower case
mystr4 = "I AM LOWER CASE"
print(mystr4.lower())

### TO access python help for any method ..hit shift + tab

i am lower case

Jupyter trick
to know about all the method() that can be used with strings,place the cursor after string and .
press tab key
mystr2.

In [ ]:
###SPLIT  - splits the string
mystr5 = "SPLIT ME PLEASE"
print(type(mystr5))
print(mystr5.split())
print(type(mystr5))
print(mystr5)
mystr5 = mystr5.split()
print(type(mystr5))

<class 'str'>
['SPLIT', 'ME', 'PLEASE']
<class 'str'>
SPLIT ME PLEASE
<class 'list'>

In [ ]:
### count gives the occrences of a given word or character in paranthesis and in the first 10 characters of the string

print("find the occurrences of the word the".count('the',0,10))

1

In [ ]:
# Scope
val = 1
def foo():
    val = 15
    print( "value = ", val)
foo()
print("value = ", val)

value =  15
value =  1

In [ ]:
# type Casting - implicit
a = 12
b = 20.0
print("type of a ", type(a))
print("type of b ", type(b))
pd = a*b
print("type of pd ", type(pd))

type of a  <class 'int'>
type of b  <class 'float'>
type of pd  <class 'float'>

In [ ]:
# typeCasting - Explicit
a = 4.6
b = int(a)
print("type of a = ", a , type(a))
print("type of b = ",b , type(b))

type of a =  4.6 <class 'float'>
type of b =  4 <class 'int'>

In [ ]:
name = 'A'
d = ord(name)
print(type(d), d)
ord('a')

<class 'int'> 65

97

In [ ]:
print(chr(65))

A

In [ ]:
stringofvalue = ord('d')
print(stringofvalue)

100

In [ ]:
# print(object(), sep=seprator, end=end,file=file, flush=flush )

print("hello", end=" ")
print("World")

print("sana.gahoi", end="@")
print("gmail.com")
print()

hello World
sana.gahoi@gmail.com

In [ ]:
print("codingHecks","are" ,"fun", sep=" ")
print("01", '10','2023', sep='-')
print('sanagahoi', 'gmail.com' , sep='@')

codingHecks are fun
01-10-2023
sanagahoi@gmail.com

### To learn about built in functions in python

- https://www.python.org

# Tuple

In [ ]:
# defining and declaring the elements in tuple

tuple1 = (['a', 1, True], 2, 'Science', -5)
print(type(tuple1))

<class 'tuple'>

In [ ]:
# Directly doing append on tuple will give error because tuples are immutable in nature
# tuple1.append('4')

# Alternatively you can reallocate the whole tuple along with value 4 to achieve the goal.
# Direct append is not possible

tuple1 = (['a', 1, True], 2, 'Science', -5, 4)
print(tuple1)

(['a', 1, True], 2, 'Science', -5, 4)

In [ ]:
# Another way is to convert the tuple in list and then perform necessary operation, then convert back into tuple

tuple1 =(['a', 1, True], 3, 'Science', -5)
tuple1 = list(tuple1)
tuple1.append(4)
print(tuple1, type(tuple1))
tuple1 = tuple(tuple1)
print(tuple1, type(tuple1))

[['a', 1, True], 3, 'Science', -5, 4] <class 'list'>
(['a', 1, True], 3, 'Science', -5, 4) <class 'tuple'>

##  Tuple indexing and slicing

In [ ]:
mytup4 = ((1, 2, 3), 199, 'a', 200.88, 'string', ('a', 'b'), [199, 299, 'pop'], [1999, 'I AM A LIST', 'Y'])
mytup4

((1, 2, 3),
 199,
 'a',
 200.88,
 'string',
 ('a', 'b'),
 [199, 299, 'pop'],
 [1999, 'I AM A LIST', 'Y'])

In [ ]:
## grab the first and last element in a tuple
print(mytup4[0])
print(mytup4[-1])
print(mytup4[7])

(1, 2, 3)
[1999, 'IAM A LIST', 'Y']
[1999, 'IAM A LIST', 'Y']

In [ ]:
### get all the elements from index 0 till index 5
print(mytup4)
print(mytup4[0:6])

((1, 2, 3), 199, 'a', 200.88, 'string', ('a', 'b'), [199, 299, 'pop'], [1999, 'IAM A LIST', 'Y'])
((1, 2, 3), 199, 'a', 200.88, 'string', ('a', 'b'))

##  Immutability in Tuples

In [ ]:
### TUPLE IMMUTABILITY CHECK
mytup4[6] = ['o','p']

TypeError: 'tuple' object does not support item assignment

### Since tuples are immutable,changing the individual items in tuple is not possible. but changing whole tuple is

In [1]:
### this is possible
my_tuple7= ((100, 200, 300),1990, 'ac', 2009.88,('x', 'y'),['I AM A LIST', 'Y'])
my_tuple7

((100, 200, 300), 1990, 'ac', 2009.88, ('x', 'y'), ['I AM A LIST', 'Y'])

In [2]:
### this is also possible - by converting a tuple to list, add a value and then reconvert back to tuple

my_list_test=list(my_tuple7)
my_list_test.append(10000)
print(type(my_list_test))
print(my_list_test)
my_list_test_tuple = tuple(my_list_test)  ### convert into a tuple
print(type(my_list_test_tuple))
print(my_list_test_tuple)

<class 'list'>
[(100, 200, 300), 1990, 'ac', 2009.88, ('x', 'y'), ['I AM A LIST', 'Y'], 10000]
<class 'tuple'>
((100, 200, 300), 1990, 'ac', 2009.88, ('x', 'y'), ['I AM A LIST', 'Y'], 10000)

##  Build in methods in Tuple
- Python has two built-in methods that you can use on tuples
  - count()
  - index()

### count() method
- The count() method returns the number of times a specified value appears in the tuple

In [ ]:
mytup4.count('a')

1

### index() method
- The index() method finds the first occurrence of the specified value
- The index() method raises an exception if the value is not found

In [ ]:
mytup4.index('a')

2

# List Methods

In [ ]:
# Defining and declaring the content of the list

list1 = [4, 5, 7, -2, 0, 1]
print(type(list1))
print(len(list1))

<class 'list'>
6

In [ ]:
# using max method to find the max element in the list
print(max(list1))

7

In [ ]:
# Applied sorted() method to sort and print the given list
print(sorted(list1))

str_list = ['d', 'bd', 'css', 'r']
print(sorted(str_list))
def len_func(n):
  return len(n)
str_list.sort(key = len_func)
print(str_list)

[-2, 0, 1, 4, 5, 7]
['bd', 'css', 'd', 'r']
['d', 'r', 'bd', 'css']

In [ ]:
#List Of String
mylist1 = ['a','b','c']
print(mylist1)
print(type(mylist1))

#List of numbers, string, floats
mylist2 = [100,199.99,'str1','c','112s']
print(mylist2)
print(type(mylist2))

['a', 'b', 'c']
<class 'list'>
[100, 199.99, 'str1', 'c', '112s']
<class 'list'>

In [ ]:
# Copying the list by using copy() method to make sure that changes happening in each lists are independent of each other

list2 = list1.copy()
print(list2)

[4, 5, 7, -2, 0, 1]

#### We can have a list within a list (nested lists)

In [ ]:
mylist3 = ['A String',100.9,200,[9,10],['a','b'], [1,2,3],['h','i','j']]
print(f"mylist3 has the values: {mylist3} ")
print(f"Length of mylist3: {len(mylist3)} ")
print(f"Type of mylist3: {type(mylist3)} ")

mylist3 has the values: ['A String', 100.9, 200, [9, 10], ['a', 'b'], [1, 2, 3], ['h', 'i', 'j']]
Length of mylist3: 7
Type of mylist3: <class 'list'>

##  List indexing and Slicing
- List indexing works similar to that of string indexing. it starts with 0
- Can b sliced like that of a string

In [ ]:
print(mylist3)
print(len(mylist3))
### indexes 0,1,2,3,4,5,6

['A String', 100.9, 200, [9, 10], ['a', 'b'], [1, 2, 3], ['h', 'i', 'j']]
7

In [ ]:
mylist3.index(200)

2

In [ ]:
### To grab 200 from mylist3
print(mylist3[2])

200

#### Here using slice notation (start:stop,step)

In [ ]:
### to grab 200,[9,10]
print(mylist3[2:4])

[200, [9, 10]]

In [ ]:
### to grab the value 9 in the nested list [9,10]
print(mylist3)
print(mylist3[3][0])
print(mylist3[3][1])

['A String', 100.9, 200, [9, 10], ['a', 'b'], [1, 2, 3], ['h', 'i', 'j']]
9
10

##  Mutability in Lists
- Lists are mutable
-  The elements of the list can be modified, individual elements can be replaced, and the order of elements can be changed even after the list has been created

In [ ]:
## update value in index 2 (2000) to "STRING2000"
mylist3[2] = "STRING2000"
print(mylist3)

### LISTS ARE MUTABLE

['A String', 100.9, 'STRING2000', [9, 10], ['a', 'b'], [1, 2, 3], ['h', 'i', 'j']]

## Built in methods in list
- To know all the built-in methods in a list use tab key after the list name
- mylist12."hit tab key"
- List methods are :
  - append()
  - extend()
  - count()
  - sort()
  - reverse() and many more

### append() method
- The append() method appends an element to the end of the list

In [ ]:
### append an item to the list
mylist3.append('append me again')
print(mylist3)

['A String', 100.9, 'STRING2000', [9, 10], ['a', 'b'], [1, 2, 3], ['h', 'i', 'j'], 'append me again']

### extend() method
- The extend() method adds the specified list elements (or any iterable) to the end of the current list

In [ ]:
mylist3.extend(['c','f'])
mylist3

['A String',
 100.9,
 'STRING2000',
 [9, 10],
 ['a', 'b'],
 [1, 2, 3],
 ['h', 'i', 'j'],
 'append me again',
 'c',
 'f']

### count() method
- The count() method returns the number of elements with the specified value

In [ ]:
mylist3.count('c')

1

### sort() method
- The sort() method sorts the list ascending by default

In [ ]:
mylist4 = ['s', 'd', 'e']
mylist4.sort()
print(mylist4)
mylist4.sort(reverse=True)
mylist4

['d', 'e', 's']

['s', 'e', 'd']

In [ ]:
class Solution:
    def merge( nums1, m, nums2, n):
        """
        Do not return anything, modify nums1 in-place instead.
        """
        for i in range(n):
            nums1[m+i] = nums2[i]
        nums1.sort()

In [ ]:
nums1 = [1,2,3,0,0,0]; m = 3; nums2 = [2,5,6]; n = 3;
Solution.merge(nums1, m, nums2, n)
print(nums1)

[1, 2, 2, 3, 5, 6]

### Sorting w.r.t specified function criteria
- We can also make a function to decide the sorting criteria(s)
- Syntax is : list.sort(reverse=True|False, key=myFunc)

In [ ]:
def len_function(q):
  return len(q)

mylist5 = ['aaaa', 'aa', 'a', 'c', 'dd', 'f']
mylist5.sort(key = len_function)
mylist5

['a', 'c', 'f', 'aa', 'dd', 'aaaa']

### reverse() method
- The reverse() method reverses the sorting order of the elements

In [ ]:
### reverse
mylist6 = ['a','b','c','d','e','a','d','d']
print(mylist6)
mylist6.reverse()
print(mylist6)

['a', 'b', 'c', 'd', 'e', 'a', 'd', 'd']
['d', 'd', 'a', 'e', 'd', 'c', 'b', 'a']

# Indexing

In [ ]:
# Decaling and defining the content of list
list1 = ['Python', 1, 2, 3, 'Data', True]

print(type(list1))

<class 'list'>

In [ ]:
# using negative indexing to print the second last element
print(list1[-2])

Data

In [ ]:
# using slicing to access the first three lement of th list
# 0 points to the beginning of the index position to access the element
# 3 represents the end index for element accessing

print(list1[0:3])
print(list1[::-1])

['Python', 1, 2]
[True, 'Data', 3, 2, 1, 'Python']

# Slicing

In [ ]:
# applied slicing methods to see the desired output

print(list1[1:len(list1):2])

[1, 3, True]

In [ ]:
# Using remove() to delete 5 from the list. This will delete only the first instance of 5 in the list.
# There is a different way to delete all the instance of same number in python

list1.remove(3)
print(list1)

['Python', 1, 2, 'Data', True]

In [ ]:
# Defining and declaring the content of the list

list1 = ['R', 'Python', 'C', 'Java']

In [ ]:
# performing the extend() operation to insert the data in the given list.
# Alternatively you can employ append as well to insert the data in list

list1.extend(['Excel', 'Data'])
print(list1)

['R', 'Python', 'C', 'Java', 'Excel', 'Data']

In [ ]:
# using for loop replace the element in the given list

for i in range(len(list1)):
    if list1[i] == 'C':
        list1[i] = 'C++'
    else:
        pass
print(list1)

['R', 'Python', 'C++', 'Java', 'Excel', 'Data']

In [ ]:
numbers = range(10)

even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

print(even_numbers)

[0, 2, 4, 6, 8]

# Dictionary Methods

In [ ]:
# declaring and defining elements in the dictionary
dictionary1 = {1:1, 2:4, 3:9}

### create dictionary
mydict0 =  {'k1':100,'k2':'str','k3':199.99,'k4':'0'}
print('\n')
print(mydict0)
print('\n')
print(type(mydict0))
print('\n')
print(len(mydict0))

{'k1': 100, 'k2': 'str', 'k3': 199.99, 'k4': '0'}


<class 'dict'>


4

In [ ]:
# using [] approach to insert/update new key value pair in dictionary.
# An alternate approach is also there to insert key-value pair in the dictionary.

dictionary1[4] = 16
print(dictionary1)

{1: 1, 2: 4, 3: 9, 4: 16}

In [ ]:
### dictionaries with lists, tuples, dictionary
mydict2= {'listkey1' : [1,2,3],  'tupkey2' : (1,2,3), 'dictkey':{'k1':1990,'k2':'a','k3':[1,2,3]}, 'strkey':'i am a string' }
print(mydict2)
print(type(mydict2))
print(len(mydict2))

{'listkey1': [1, 2, 3], 'tupkey2': (1, 2, 3), 'dictkey': {'k1': 1990, 'k2': 'a', 'k3': [1, 2, 3]}, 'strkey': 'i am a string'}
<class 'dict'>
4

In [ ]:
mydict2[2]

KeyError: 2

In [ ]:
### call the dictionary using keyvalue
mydict2['dictkey']

{'k1': 1990, 'k2': 'a', 'k3': [1, 2, 3]}

In [ ]:
### having the same key names with multiple elements will result in one key being retained
mydict2= {'listkey1' : [1,2,3],  'listkey1' : [10,2,3], 'dictkey':{'k1':1990,'k2':'a','k3':[1,2,3]}, 'strkey':'i am a string' }
print(mydict2)

{'listkey1': [10, 2, 3], 'dictkey': {'k1': 1990, 'k2': 'a', 'k3': [1, 2, 3]}, 'strkey': 'i am a string'}

In [ ]:
### keys in dictionaries can be numbers
mydict3= {1000 : [1,2,3],  2000 : (1,2,3)}
print(mydict3[1000])
print(mydict3[1000][1])

[1, 2, 3]
2

In [ ]:
### special chars are not allowed while defining a dictionary key
mydict3= {$$$ : [1,2,3],  2000 : (1,2,3)}

SyntaxError: invalid syntax (1951820012.py, line 2)

### DICTIONARIES CANNOT HAVE A MUTABLE OBJECT AS KEY

In [ ]:
### IN THIS CASE THERE IS A LIST [1,1] as a key AND RESULTS IN ERROR
mydict7 = {[1, 1]: 'a', (1, 2): 'b', (2, 1): 'c', (2, 2): 'd'}   ### this is NOT accepted

TypeError: unhashable type: 'list'

In [ ]:
### even a dictionary will not work as a key -- as dictionary is mutable
mydict8 = {{'k1': 1}: 'a', (1, 2): 'b', (2, 1): 'c', (2, 2): 'd'}   ### this is NOT accepted

TypeError: unhashable type: 'dict'

## 9.2 Indexing, Slicing in Dictionaries

In [ ]:
print(mydict2)

{'listkey1': [10, 2, 3], 'dictkey': {'k1': 1990, 'k2': 'a', 'k3': [1, 2, 3]}, 'strkey': 'i am a string'}

In [ ]:
### to grab the first element of the key "dictkey"
mydict2['dictkey']['k1']

1990

### SLICING OR SLICE NOTATION DOES NOT WORK

In [ ]:
mydict9 =  {0: 'a', 1: 'b', 2: 'c', 3: 'd'}
print(mydict9[-1])

KeyError: -1

In [ ]:
print(mydict9[0:2])     #### NOT ACCEPTABLE

TypeError: unhashable type: 'slice'

## 9.3 Methods in dictionaries
- Python has various methods to work in dictionaries:
  - keys()
  - values()
  - items()
  - get()
  - update() and many more

In [ ]:
mydict10 = {'key1':123,'key2':[12,23,33],'key3':['item0','item1','item2'],'key4':{'sk1':1,'sk2':2}}
mydict10.get("key1")

123

### keys() method
- The keys() method returns a view object
- The view object contains the keys of the dictionary, as a list
- The view object will reflect any changes done to the dictionary

In [ ]:
### to get the keys in a dictionary
mydict10.keys()

dict_keys(['key1', 'key2', 'key3', 'key4'])

### values() method
- The values() method returns a view object
- The view object contains the values of the dictionary, as a list
- The view object will reflect any changes done to the dictionary

In [ ]:
### to get the values in a dictionary
mydict10.values()

dict_values([123, [12, 23, 33], ['item0', 'item1', 'item2'], {'sk1': 1, 'sk2': 2}])

### items() method
- The items() method returns a view object
- The view object contains the key-value pairs of the dictionary, as tuples in a list
- The view object will reflect any changes done to the dictionary

In [ ]:
### to get the items(key and value) in a dictionary
mydict10.items()

dict_items([('key1', 123), ('key2', [12, 23, 33]), ('key3', ['item0', 'item1', 'item2']), ('key4', {'sk1': 1, 'sk2': 2})])

#  Sets in Python
- An unordered collection data type
- Iterable and mutable
- Do not allow duplicate elements
-  Since sets are unordered, we cannot access items using indexes like we do in lists
-  Python’s Set class represents the mathematical notion of a set
- The major advantage of using a set, as opposed to a list, is that it has a highly optimized method for checking whether a specific element is contained in the set

In [ ]:
# We can create sets using set() in build function or putting elements in {}
new_set = {11, 22, 33}
new_set

{11, 22, 33}

In [ ]:
type(new_set)

set

In [ ]:
# check the length of set
len(new_set)

3

In [ ]:
new_set1 = set([13, 14, 16, 45])
new_set1

{13, 14, 16, 45}

In [ ]:
# set does not allow duplicate values
new_set2 = set([1, 3, 3, 5, 10])
new_set2   # returns only unique values

{1, 3, 5, 10}

In [ ]:
# set can have different data types
set1 = {"ABC", 4, True, 40, "Male"}
set1

{4, 40, 'ABC', 'Male', True}

## Frozen Set
- Frozen sets are a native data type in Python that have the qualities of sets including class methods — but are immutable like tuples
- To use a frozen set, call the function frozenset() and pass an iterable as the argument
- If you pass a set to the function, it will return the same set, which is now immutable

In [ ]:
professor = {"name": "Raj", "age": 42, "sex": "Male",
           "college": "NIT Aurangabad", "address": "Aurangabad"}

# Lets make keys of dictionary as frozenset
frozen_keys = frozenset(professor)
print(f"The frozen set is: {frozen_keys} ")

The frozen set is: frozenset({'name', 'college', 'address', 'age', 'sex'})

### Frozenset object is immuable, throws error if trying to change value

In [ ]:
languages = ["Python", "Java", "C++"]

frozen_languages = frozenset(languages)

# throws error for:
frozen_languages[1] = "C"

TypeError: 'frozenset' object does not support item assignment

##  Set methods in Python
- add()
- union()
- intersection()
- difference() and more

### add() method
- The add() method adds an element to the set
- If the element already exists, the add() method does not add the element

In [ ]:
new_set

{11, 22, 33}

In [ ]:
new_set.add(44)

In [ ]:
new_set

{11, 22, 33, 44}

In [ ]:
new_set.add(11)
new_set  # does not add if already present in set

{11, 22, 33, 44}

### union() method
- The union() method returns a set that contains all items from the original set, and all items from the specified set(s)
- We can specify as many sets you want, separated by commas
- It does not have to be a set, it can be any iterable object
- If an item is present in more than one set, the result will contain only one appearance of this item

In [ ]:
# Union of sets
new_set4 = {"Python", "data"}
ml = {"Linear regression", "KNN"}
dl = {"Ensemble", "NLP"}
language = {"Python", "R"}
data_science = new_set4.union(dl)
print(data_science)

{'data', 'NLP', 'Ensemble', 'Python'}

### intersection() method
- The intersection() method returns a set that contains the similarity between two or more sets
- The returned set contains only items that exist in both sets, or in all sets if the comparison is done with more than two set

In [ ]:
set1 = set()
set2 = set()

for i in range(5):
    set1.add(i)
for i in range(3,9):
    set2.add(i)

set3 = set1.intersection(set2)

print("Intersection using intersection() function")
print(set3)

# Intersection using "&" operator
set3 = set1 & set2

print("\nIntersection using '&' operator")
print(set3)

Intersection using intersection() function
{3, 4}

Intersection using '&' operator
{3, 4}

# Comprehensions in Python
- A short and concise way to construct new sequences (such as lists, set, dictionary etc.) using sequences which have been already defined
- List comprehension
- List comprehension syntax: output_list = [output_exp for var in input_list if (var satisfies this condition)]
- Dictionary comprehension
- Dictionary comprehension syntax: output_dict = { key: value for (key, value) in Iterable if (key, value satisfy this condition)}
- Set comprehension

### List comprehension

In [ ]:
list_1 = [1, 2, 3, 4, 4, 5, 6, 7, 7]
list_output = []

for value in list_1:
    if value % 2 == 0:
        list_output.append(value)

print("result :", list_output)

result : [2, 4, 4, 6]

In [ ]:
list_1 = [1, 2, 3, 4, 4, 5, 6, 7, 7]

comprehension_list = [value for value in list_1 if value % 2 == 0]

print("result :", comprehension_list)

result : [2, 4, 4, 6]

### Dictionary comprehension

In [ ]:
list_1 = [1,2,3,4,5,6,7]

comprehension_dict = {value:value ** 3 for value in list_1 if value % 2 != 0}

print("result :", comprehension_dict)

result : {1: 1, 3: 27, 5: 125, 7: 343}

In [ ]:
fru=["banana","apple"]
for i in range(len(fru)):
  print(fru[i])
  fruits.remove(fru[i])

### Set comprehension

In [ ]:
list_1 = [1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 7]

comprehension_set = {value for value in list_1 if value % 2 == 0}

print("result :", comprehension_set)

result : {2, 4, 6}

In [ ]:
var = "James " * 2 *3
print(var)

James James James James James James

In [ ]:
sampleSet = {"Jodi", "Eric", "Garry"}
print(sampleSet)
sampleSet.add(1, "Vicky")
print(sampleSet)

{'Eric', 'Jodi', 'Garry'}

TypeError: set.add() takes exactly one argument (2 given)

In [ ]:
x= 36/4*(3+2)*4 + 2
print(x)

182.0

In [ ]:
p, q, r = 10, 20 ,30
print(p, q, r)

10 20 30

In [ ]:
for i in range(1, 5):
    print(i, end=" ")
else:
    print("\nthis is else block statement" )

1 2 3 4
this is else block statement

In [7]:
sampleList = ['john', 'kelly', 'peter']

sampleList[2] = 'Johny'
print(sampleList)

sampleList.append(2, 'Scott')
print(sampleList)

['john', 'kelly', 'Johny']

TypeError: list.append() takes exactly one argument (2 given)

In [8]:
sampleList.insert(2, 'scott')
sampleList

['john', 'kelly', 'scott', 'Johny']

In [9]:
sampleList.insert(2, 'scott')
sampleList

['john', 'kelly', 'scott', 'scott', 'Johny']

In [ ]:
list1 = [20, 40, 60, 80]
list2 = [20, 40, 60, 80]
print(list1 == list2)
print(list1 is list2)
print(id(list1))
print(id(list2))

True
False
135068729571456
135068729567744

In [ ]:
salary = 8000

def printSalary():
  salary = 12000
  print("Salary:", salary)

printSalary()
print("Salary:", salary)

Salary: 12000
Salary: 8000

# ITP Mini Project

We all have to maintain our own personal expenses in day to day life. It’s very normal for us to lose track of them and end up going out of budget. We require a way to keep ourself in within budget.

This is where we can explore our skills in Python to come up with a solution. We can create a python program that allows you to keep track of the finance expenses.

With the Finance Tracker, users can easily set a budget and add up their expenses to make better financial decisions. Anything beyond the budget will not be added up.

**Objective:**To Estimate the Personal Financial Budget at the End of the Month.

In [ ]:
def budget_handler(salary, expense):
  salary = int(input("Enter the salary amount : "))
  expense = int(input("Enter the expense amount : "))
  if expense > salary or salary == 0:
    print("You don't have enough amount left")
  else:
    while salary >= 0:
      savings = salary - expense
      print("You have amount Rs. " , savings, " left in your account. ")
      salary = salary - expense
      print("salary ", salary)
      print("expense", expense)
      expense = int(input("enter another expense "))


budget_handler(salary, expense)

Enter the salary amount : 100
Enter the expense amount : 20
You have amount Rs.  80  left in your account.
salary  80
expense 20
enter another expense 30
You have amount Rs.  50  left in your account.
salary  50
expense 30
enter another expense 52
You have amount Rs.  -2  left in your account.
salary  -2
expense 52

KeyboardInterrupt: Interrupted by user

In [ ]:
import math
math.pow(2,3)

8.0

In [12]:
def calculate (num1, num2=4):
  res = num1 * num2
  print(res)

calculate(5)
calculate(5, 6)

20
30

In [ ]:
for x in range(0.5, 5.5, 0.5):
  print(x)

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
x = 19
print(x)
del x
print(x)

19

NameError: name 'x' is not defined

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [ ]:
help('keywords')

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not

In [ ]:
class student:
  def __init__(self, name, age, gender):
    self.name = name
    self.age = age
    self.gender = gender
  def display(self):
    print(self.name, self.age, self.gender);

s1 = student("John", 20, "Male")
s1.display()

John 20 Male

In [ ]:
with open("sample.txt", "r") as f:
  print(f.read())

sapna gupta

In [14]:
# will work in .py file

import asyncio

async def main():
    print('hello')
    await asyncio.sleep(2)
    print('world')

if __name__ == '__main__':
  asyncio.run(main())

RuntimeError: asyncio.run() cannot be called from a running event loop

In [ ]:
import asyncio
import time

async def say_after(delay, what):
    await asyncio.sleep(delay)
    print(what)

async def main():
    print(f"started at {time.strftime('%X')}")

    await say_after(1, 'hello')
    await say_after(2, 'world')

    print(f"finished at {time.strftime('%X')}")

asyncio.run(main())

RuntimeError: asyncio.run() cannot be called from a running event loop

In [ ]:
import asyncio

async def main():
    print("Hello, world!")

asyncio.get_event_loop().run_until_complete(main())

RuntimeError: This event loop is already running

In [ ]:
def combinations(iterable, r):
  pool = tuple(iterable)
  n = len(pool)
  if r>n:
    return
  indices = list(range(r))
  yield tuple(pool[i] for i in indices)
  while True:
    for i in reversed(range(r)):
      if indices[i] != i+n-r:
        break
    else:
      return
    indices[i] += 1
    for j in range(i+1, r):
      indices[j] = indices[j-1]+1
    yield tuple(pool[i] for i in indices)

Exception ignored in: <coroutine object main at 0x7ad823935700>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
Exception ignored in: <coroutine object main at 0x7ad823935700>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
Exception ignored in: <coroutine object main at 0x7ad823936d50>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'

In [ ]:
v = combinations('ABCD', 2)
print(list(r for r in v))

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

In [ ]:
def fib_gen(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b


res = fib_gen(10)
print(list(r for r in res))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [ ]:
for _ in range(10):
  print(_, end=" ")

0 1 2 3 4 5 6 7 8 9

In [ ]:
def fibo(n):
  a, b = 0, 1
  while a<n:
    yield a
    a,b = b, a+b

res = fibo(7)
print(list(r for r in res))

[0, 1, 1, 2, 3, 5]

In [ ]:
import pandas as pd

data = {
    "sales_person": ["Alice", "Bob", "Charlie", "David"],
    "sale_amount": [100, 200, 300, 400],
}
df = pd.DataFrame(data)

threshold = 250
df["above_threshold"] = df["sale_amount"].apply(
    lambda x: True if x >= threshold else False
)
df

  sales_person  sale_amount  above_threshold
0        Alice          100            False
1          Bob          200            False
2      Charlie          300             True
3        David          400             True

In [ ]:
from functools import reduce

# Define a list of numbers
numbers = range(10)

# Use map(), filter(), and reduce() to preprocess and aggregate the list of numbers
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
squares = list(map(lambda x: x**2, even_numbers))

sum_of_squares = reduce(lambda x, y: x + y, squares)
print( even_numbers)
print("squares: ", squares)
print(f"Sum of the squares of even numbers: {sum_of_squares}")

[0, 2, 4, 6, 8]
squares:  [0, 4, 16, 36, 64]
Sum of the squares of even numbers: 120

In [15]:
# dictionary comprehension
_dict = {var:var ** 2 for var in range(1, 11) if var % 2 != 0}

# set comprehension
# create a set of squares of numbers from 1 to 10
_set = {x**2 for x in range(1, 11)}

# generator comprehension
_gen = (x**2 for x in range(1, 11))

print(_dict)
print(_set)
print(_gen)
print(list(g for g in _gen))

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81}
{64, 1, 4, 36, 100, 9, 16, 49, 81, 25}
<generator object <genexpr> at 0x79557d07d7d0>
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
for idx, value in enumerate(["a", "b", "c", "d"]):
    if idx % 2 == 0:
        print(value)

a
c

In [ ]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]

# iterate over both arrays simultaneously
for a, b in zip(x, y):
    print(a, b, a + b, a * b)

1 5 6 5
2 6 8 12
3 7 10 21
4 8 12 32

In [ ]:
data = [1, 3, 5, 7]
print(any(x % 2 == 0 for x in data))
print(all(x % 2 == 1 for x in data))

False
True

In [ ]:
import random

def random_numbers():
    while True:
        yield random.random()

# Use next() to find the first number greater than 0.9
num = next(x for x in random_numbers() if x > 0.9)

print(f"First number greater than 0.9: {num}")

First number greater than 0.9: 0.9802904777923527

In [ ]:
from collections import defaultdict

count = defaultdict(int)
for item in ['a', 'b', 'a', 'c', 'b', 'a']:
    count[item] += 1

count

defaultdict(int, {'a': 3, 'b': 2, 'c': 1})

Here we use partial to create a new function increment from the existing add function with one of its arguments fixed to the value 1.

Calling increment(1) is essentially calling add(1, 1)partial is a function in the functools module that allows for creating a new function from an existing function with some of its arguments pre-filled.

partial can be useful for creating custom functions or data transformations with specific parameters or arguments pre-filled. This can help to reduce the amount of boilerplate code needed when defining and calling functions.

In [ ]:
from functools import partial

def add(x, y):
    return x + y

increment = partial(add, 1)
increment(1)

2

In [16]:
from functools import lru_cache

@lru_cache(maxsize=None)
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

fibonacci(13)

233

In [ ]:
x = 10
y = 20

print(f"x = {x}, y = {y}")
print(f"{x = }, {y = }")

# math operations
print(f"{x * y = }")

x = 10, y = 20
x = 10, y = 20
x * y = 200

In [ ]:
number = 420

# decimal places
print(f"number: {number:.2f}")

# hex conversion
print(f"hex: {number: #0x}")

# binary conversion
print(f"binary: {number:b}")

# octal conversion
print(f"octal: {number:o}")

# scientific notation
print(f"scientific: {number:e}")

# total number of characters
print(f"Number: {number:09}")

number: 420.00
hex: 0x1a4
binary: 110100100
octal: 644
scientific: 4.200000e+02
Number: 000000420

In [ ]:
apple_marketcap = 2.626 * 10e12

print(f"{apple_marketcap = :,}") # comma separator

percentage = 10.394394

print(f"{percentage = :.2%}") # percentage

apple_marketcap = 26,260,000,000,000.0
percentage = 1039.44%

In [ ]:
import datetime

today = datetime.datetime.utcnow()
print(f"datetime : {today}\n")

print(f"date time: {today:%m/%d/%Y %H:%M:%S}")
print(f"date: {today:%d/%m/%Y}")
print(f"time: {today:%H:%M:%S.%f}")
print(f"time: {today:%H:%M:%S %p}")
print(f"time: {today:%H:%M}")

datetime : 2024-07-24 12:24:22.043050

date time: 07/24/2024 12:24:22
date: 24/07/2024
time: 12:24:22.043050
time: 12:24:22 PM
time: 12:24

In [ ]:
# Locale’s appropriate date and time representation
print(f"locale appropriate: {today:%c}")

# weekday
print(f"weekday: {today:%A}")

# day of the year
print(f"day of year: {today:%j}")

# how far are we into the year?
day_of_year = f"{today:%j}"
print(f"progress % year: {int(day_of_year)/365 * 100:.2f}%")

locale appropriate: Wed Jul 24 12:24:22 2024
weekday: Wednesday
day of year: 206
progress % year: 56.44%

If you write OOP in Python, you’d be familiar with the dunder methods __repr__ and __str__

The basic idea is:

__repr__= developer friendly
__str__ = user friendly
Below is an example of a dataclass Person with name and age attributes.

For a dataclass, by default (without a str method defined), printing the object will give you the output of repr.

With a str the method defined, you’d need to write !r to tell Python to print out the repr method instead.

In [ ]:
from dataclasses import dataclass

@dataclass
class Person:
    name : str
    age : int

    def __str__(self) -> str:
        return f"{self.name} is {self.age} years old"

Elon = Person("Elon Musk", 51)
print(f"{Elon}") # str
print(f"{Elon!r}") # repr

Elon Musk is 51 years old
Person(name='Elon Musk', age=51)

In [ ]:
number = 4
print(f"number is {number:4}") # width of 10

# numbers
for number in range(1, 5):
    print(f"the number is {number:{number}}")

left = "left text"
center = "center text!"
right = "right text"

print(f"{left:<20}") # left align
print(f"{center:^20}") # center align
print(f"{right:>20}") # right align

print(f"{left : <20}{center : ^20}{right : >20}")

number is    4
the number is 1
the number is  2
the number is   3
the number is    4
left text
    center text!
          right text
left text               center text!              right text

In [ ]:
company_name = "Tesla"
employee_count = 100000
mission = "To accelerate the world's transition to sustainable energy"

print(f"""
Company: {company_name}
# of employees: {employee_count:,}
Mission: {mission}
""")

Company: Tesla
# of employees: 100,000
Mission: To accelerate the world's transition to sustainable energy

Read from multiple files
Is your data in multiple files? Read them all in with glob!

In [ ]:
import glob
import os

files = glob.glob("file_*.csv")

result = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

Looking at some data on Excel but don’t want to download it? Copy it! Pandas can read from your clipboard.

In [ ]:
df = pd.read_clipboard()

 Read tables from PDF files

In [ ]:
# %pip install tabula-py

from tabula import read_pdf
# Read pdf into list of DataFrame
df = read_pdf('test.pdf', pages='all')

Want to visualize your dataset but don’t want to write code for plots? With pandas-profiling, you can do it with just one line of code.

In [ ]:
# !pip install ydata-profiling

In [4]:
# %pip install pandas-profiling - we kinda not using bcs it didn't work
import seaborn as sns
import ydata_profiling as pp

df = sns.load_dataset("titanic")
profile = df.profile_report(title="Pandas Profiling Report")
profile.to_file(output_file="output.html")

/tmp/ipykernel_553/3167729330.py:3: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  import ydata_profiling as pp

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
  7%|▋         | 1/15 [00:00<00:02,  5.23it/s]
 53%|█████▎    | 8/15 [00:00<00:00, 28.23it/s]
100%|██████████| 15/15 [00:00<00:00, 32.87it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
# Are your numeric columns read in as objects? Let pandas do the work in converting them!
df.infer_objects().dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [7]:
import pandas as pd

# Pandas’ to_numeric has a nifty feature to downcast the type, allowing you to reduce the data frame’s size.
pd.to_numeric(df.numeric_col, downcast="integer") # smallest signed int dtype
pd.to_numeric(df.numeric_col, downcast="float")  # smallest float dtype

AttributeError: 'DataFrame' object has no attribute 'numeric_col'

In [ ]:
# If there are NaN values in the data, errors="coerce" can help prevent those nasty errors. At the same time, you can fill those NA values with reasonable values using .fillna
# apply to whole data frame
df = df.apply(pd.to_numeric, errors="coerce")

# apply to specific columns
pd.to_numeric(df.numeric_column, errors="coerce")

# filling NA values with zero
pd.to_numeric(df.numeric_column, errors="coerce").fillna(0)

In [ ]:
import numpy as np

random_col = np.random.randint(10, size=len(df))
df.insert(3, 'random_col', random_col) # inserts at third column

In [ ]:
df["logic"] = np.where(df["price"] > 5, "high", "low")

In [ ]:
pattern = '([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

df['email'].str.findall(pattern, flags=re.IGNORECASE)

Creating a Simple API using Python with Flask:

In [ ]:
# File: app.py

from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/custom-api')
def custom_api():
    data = {
        'message': 'Hello, World!'
    }
    return jsonify(data)

if __name__ == '__main__':
  app.run(debug == True)

In [ ]:
class Dog:

	# A simple class
	# attribute
	attr1 = "mammal"
	attr2 = "dog"

	# A sample method
	def fun(self):
		print("I'm a", self.attr1)
		print("I'm a", self.attr2)

# Driver code
# Object instantiation
Rodger = Dog()

# Accessing class attributes
# and method through objects
print( "To print a particular attribute like attr1 -> ", Rodger.attr1)
Rodger.fun()

To print a particular attribute like attr1 ->  mammal
I'm a mammal
I'm a dog

In [ ]:
# Python code to demonstrate how parent constructors are called.

# parent class
class Person(object):

	# __init__ is known as the constructor
	def __init__(self, name, idnumber):
		self.name = name
		self.idnumber = idnumber

	def display(self):
		print(self.name)
		print(self.idnumber)

	def details(self):
		print("My name is {}".format(self.name))
		print("IdNumber: {}".format(self.idnumber))

# child class
class Employee(Person):
	def __init__(self, name, idnumber, salary, post):
		self.salary = salary
		self.post = post

		# invoking the __init__ of the parent class
		Person.__init__(self, name, idnumber)

	def details(self):
		print("My name is {}".format(self.name))
		print("IdNumber: {}".format(self.idnumber))
		print("Post: {}".format(self.post))


# creation of an object variable or an instance
a = Employee('Rahul', 886012, 200000, "Intern")

# calling a function of the class Person using
# its instance
a.display()
a.details()

Rahul
886012
My name is Rahul
IdNumber: 886012
Post: Intern

In [ ]:
(0.1+0.2) -0.3

5.551115123125783e-17

In [ ]:
0.1+0.2

0.30000000000000004

In [ ]:
0.3-(0.1+0.2)

-5.551115123125783e-17

In [ ]:
0.2-0.1

0.1

In [ ]:
0.1-0.2

-0.1

In [ ]:
0.7-0.4

0.29999999999999993

In [ ]:
0.9-0.6

0.30000000000000004

In [ ]:
0.5-0.2

0.3

In [ ]:
0.6-0.3

0.3

In [ ]:
# to generate random number in numpy we use rand(no. of matrix,rows,columns)
import numpy as np
print(np.random.rand(2,2,3))

[[[0.27820913 0.92332872 0.17320648]
  [0.61366769 0.5875278  0.41298413]]

 [[0.80126111 0.98554489 0.47223605]
  [0.48208592 0.98044735 0.76398192]]]

In [ ]:
# Return random integers from low (inclusive) to high (exclusive).
# syntax: np.random.randint(start,end,size(row,col))
print(np.random.randint(10,20))
print(np.random.randint(10,20,(2,3)))

14
[[10 10 19]
 [18 10 10]]

In [ ]:
arr= np.arange(0, 50)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

In [ ]:
arr[33]
arr[3:7]
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

zxc=np.arange(1,31)
print(zxc)
zxc=zxc.reshape(5,6)
zxc

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
zxc[[1,2,4,4,3,1],[3,4,4,1,0,3]]
#zxc[[row1,row2,row3,row4],[col1,col2,col3,col4]]

array([10, 17, 29, 26, 19, 10])

In [ ]:
np.arange(200,250).reshape(10,5)

array([[200, 201, 202, 203, 204],
       [205, 206, 207, 208, 209],
       [210, 211, 212, 213, 214],
       [215, 216, 217, 218, 219],
       [220, 221, 222, 223, 224],
       [225, 226, 227, 228, 229],
       [230, 231, 232, 233, 234],
       [235, 236, 237, 238, 239],
       [240, 241, 242, 243, 244],
       [245, 246, 247, 248, 249]])

In [ ]:
print(np.arange(1,10))
print(np.linspace(1,10))

[1 2 3 4 5 6 7 8 9]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]

In [ ]:
twoD = np.array([[1,2,3,4],[3,4,5,7]])
oneD = twoD.ravel()
print(oneD)

[1 2 3 4 3 4 5 7]

In [ ]:
lst = [[1,2,3,4],[3,4,5,7]]
twoD = np.array(lst)
oneD = twoD.ravel()
print(oneD)
print(type(oneD))
oneD = list(oneD)
print(oneD)
print(type(oneD))

[1 2 3 4 3 4 5 7]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 3, 4, 5, 7]
<class 'list'>

In [ ]:
_1d = np.array([1,2,3,4])
traversed_arr = _1d.reshape(-1,1)
print(_1d)
print(traversed_arr)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]

In [ ]:
marks=np.array([2,5,2,8,5,9,5,4,5])
#unique with count
uni,count=np.unique(marks,return_counts=True)  # it will give u array of unique values in array marks
print(count)
arr = np.arange(0,11)
print(np.log(arr))

[2 1 4 1 1]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]

<ipython-input-27-e1a71491921c>:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))

In [ ]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

5.0
5.0
3.1622776601683795
10.0

In [8]:
import numpy as np
np.random.seed(10)
data = np.random.normal(100, 20, 200)
print(data)

[126.63173008 114.30557949  69.09199416  99.832323   112.42671948
  85.59828879 105.31023171 102.17097051 100.08582862  96.50799579
 108.6605238  124.06074748  80.69868659 120.56548156 104.5726026
 108.90275226  77.26795576 102.70273757 129.69074004  78.40390228
  60.44543439  65.13255408 105.32140328 147.69934661 122.47382507
 133.45244427 101.98298432 127.95992754  94.57504024 112.2640837
  94.65365623  89.01381972 102.65416592  90.4771597  126.16946162
 103.90026558 108.00419977  93.24735326 125.12944528  85.36060996
 113.20463102  92.98256217  81.2113328   90.21325566  83.90817715
  95.74604723  93.21719508 106.24339873 111.30305339  97.05159485
  99.48189326 105.78188408  89.20241857 114.1632004  116.84449477
 104.07161595 147.8940733  118.34917875  97.75455058  92.75639106
  95.35635488  89.96542201 122.57570306  86.04379939  98.37755632
  89.41407838 120.92365714  71.62887942  92.75001634  97.56188618
 106.38712842 109.21805803  95.68420215 119.78144915 106.29507558
 149.35302113  69.83357026 112.41201326  79.09734925  84.03982365
 139.70169183 134.89628297  62.87629039  95.54452602  98.68304305
  57.36575783  99.02338977 107.86682434 104.3453029   60.11212461
 122.1541647  104.89087953  98.76175941  84.92214079 114.23918033
 118.36538303  90.35813722 101.79175225 116.53997245  60.9097576
 102.34951322  61.85086224  81.5418147  109.39502868  97.11266474
  91.99723296  94.08032294 116.96417218 114.1366091   84.25462148
 105.8588145   90.58385497 148.08651212  85.21286523  93.74342485
  93.02236164  91.21947528 102.82208336 105.4609864   67.62858504
  88.53773277  73.59104908 124.72410652 149.30650164 127.66464459
 106.92466231 120.45032214 103.33620534 133.13433249 113.35779218
  95.40106712  77.40897611  87.20074792 106.27661043  75.48328039
  95.56413727 126.7985262  100.58619422 139.70771492 128.94331201
  94.24741173  72.81378854  99.0391735   90.3842532  107.55506172
 132.28815948  77.5379193   92.22544106 106.64699899 122.69946346
 110.21428823 108.28595282 126.89098847 109.87030634  95.25991631
 101.145703    85.85857106 110.93329675 118.85000818  40.40806458
 124.36297701  98.86958554 109.21776905 113.24748023  54.09793342
  76.08141377  93.33797676  84.17218458 105.48345562  89.70180155
  65.77857606 112.24594625 122.00258748 111.28705053  85.74401126
  94.78281043 110.96856133 112.063981   120.13722277  94.11147985
  71.5823897   86.42106451 110.67769619 114.87948808 144.50099278
 102.3436284  104.89229041  96.45402355  91.88540945 115.63550381
 107.06955228  95.85441029  78.40605232  97.53860343  92.18035629
 125.10347463 118.94252156  79.55378615 123.34336737  88.56046373]