# Typing Speeds

How can you improve your typing speed?

The file `typing-speeds.csv` contains typing speed data from >168,000 people typing 15 sentences each. The data was collected via an online typing test published at a free typing speed assessment webpage.

In [8]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'typing-speeds.csv'.

# from google.colab import files
# uploaded = files.upload()

In [11]:
import pandas as pd

df = pd.read_csv('typing-speeds.csv')
df

,PARTICIPANT_ID,AGE,HAS_TAKEN_TYPING_COURSE,COUNTRY,LAYOUT,NATIVE_LANGUAGE,FINGERS,KEYBOARD_TYPE,ERROR_RATE,AVG_WPM_15,ROR
0,3,30,0,US,qwerty,en,1-2,full,0.511945,61.9483,0.2288
1,5,27,0,MY,qwerty,en,7-8,laptop,0.871080,72.8871,0.3675
2,7,13,0,AU,qwerty,en,7-8,laptop,6.685633,24.1809,0.0667
3,23,21,0,IN,qwerty,en,3-4,full,2.130493,24.7112,0.0413
4,24,21,0,PH,qwerty,tl,7-8,laptop,1.893287,45.3364,0.2678
...,...,...,...,...,...,...,...,...,...,...,...
168589,517932,20,0,US,qwerty,en,9-10,laptop,8.731466,24.9125,0.1842
168590,517936,25,0,PL,qwerty,pl,9-10,laptop,0.000000,66.2946,0.0639
168591,517943,38,1,US,qwerty,en,9-10,laptop,0.147929,75.6713,0.2021
168592,517944,28,0,GB,qwerty,en,9-10,laptop,0.278552,91.7083,0.5133
168593,517947,51,0,GB,qwerty,en,7-8,laptop,0.000000,56.8787,0.3409



| **Variable**             | **Description**                                                                 |
|--------------------------|---------------------------------------------------------------------------------|
| `PARTICIPANT_ID`         | Unique ID of the participant                                                   |
| `AGE`                    | Age of the participant                                                         |
| `HAS_TAKEN_TYPING_COURSE`| Whether the participant has taken a typing course (1 = Yes, 0 = No)            |
| `COUNTRY`                | Country of the participant                                                     |
| `LAYOUT`      		   | Keyboard layout used (QWERTY, AZERTY, or QWERTZ)                               |
| `NATIVE_LANGUAGE`        | Native language of the participant                                             |
| `FINGERS`                | Number of fingers used for typing (options: 1-2, 3-4, 5-6, 7-8, 9-10)          |
| `KEYBOARD_TYPE`          | Type of keyboard used (Full/desktop, laptop, small physical, or touch)         |
| `ERROR_RATE(%)`          | Uncorrected error rate (as a percentage)                                       |
| `AVG_WPM_15`             | Words per minute averaged over 15 typed sentences                              |
| `ROR`                    | Rollover ratio                                                                 |

### Project Ideas
- Remove unnecessary columns, such as PARTICIPANT_ID, to streamline the dataset.

- Rename columns (e.g `AVG_WPM_15` to `wpm`, `ROR` to `ror`, `HAS_TAKEN_TYPING_COURSE` to `course`) for brevity and clarity during analysis.

Finger Count Analysis
- Compare typing speeds across groups using different numbers of fingers, excluding the "10+" category for simplicity.

- Control for consistency by first filtering to similar `AGE`, `KEYBOARD_LAYOUT`, `NATIVE_LANGUAGE`, `KEYBOARD_TYPE`, and `HAS_TAKEN_TYPING_COURSE` values.

- Exclude participants with high error rates (ERROR_RATE > 3%) to focus on reliable data.

- Drop columns after filtering if they now only have a single value.

Rollover Ratio Analysis
- The Rollover Ratio (`ROR`) represents the proportion of keypresses where a new key is pressed before releasing the previous one.

- Compare typing speeds between participants with `ROR` ≤ 20% and those with `ROR` > 80%, keeping `AGE`, `KEYBOARD_TYPE`, `FINGERS`, and other variables constant.

Influence of Typing Course
- Compare typing speeds between participants with a typing course (`HAS_TAKEN_TYPING_COURSE` = 1) and without (`HAS_TAKEN_TYPING_COURSE` = 0), holding other variables such as `KEYBOARD_TYPE`, `AGE` range, and `FINGER_COUNT` constant.

In [12]:
# Remove unnecessary columns, such as PARTICIPANT_ID, to streamline the dataset.
df = df.drop(columns='PARTICIPANT_ID')
df

,AGE,HAS_TAKEN_TYPING_COURSE,COUNTRY,LAYOUT,NATIVE_LANGUAGE,FINGERS,KEYBOARD_TYPE,ERROR_RATE,AVG_WPM_15,ROR
0,30,0,US,qwerty,en,1-2,full,0.511945,61.9483,0.2288
1,27,0,MY,qwerty,en,7-8,laptop,0.871080,72.8871,0.3675
2,13,0,AU,qwerty,en,7-8,laptop,6.685633,24.1809,0.0667
3,21,0,IN,qwerty,en,3-4,full,2.130493,24.7112,0.0413
4,21,0,PH,qwerty,tl,7-8,laptop,1.893287,45.3364,0.2678
...,...,...,...,...,...,...,...,...,...,...
168589,20,0,US,qwerty,en,9-10,laptop,8.731466,24.9125,0.1842
168590,25,0,PL,qwerty,pl,9-10,laptop,0.000000,66.2946,0.0639
168591,38,1,US,qwerty,en,9-10,laptop,0.147929,75.6713,0.2021
168592,28,0,GB,qwerty,en,9-10,laptop,0.278552,91.7083,0.5133
168593,51,0,GB,qwerty,en,7-8,laptop,0.000000,56.8787,0.3409

In [15]:
''' Rename columns (e.g AVG_WPM_15 to wpm, ROR to ror, HAS_TAKEN_TYPING_COURSE to course)
for brevity and clarity during analysis. '''

df = df.rename(columns={
    'AVG_WPM_15': 'wpm',
    'ROR' : 'ror',
    'HAS_TAKEN_TYPING_COURSE':'course',
    'AGE': 'age',
    'COUNTRY': 'country',
    'LAYOUT':'layout',
    'NATIVE_LANGUAGE': 'native_language',
    'FINGERS' : 'fingers',
    'KEYBOARD_TYPE' : 'keyboard_type',
    'ERROR_RATE':'error_rate'   
})
df

,age,course,country,layout,native_language,fingers,keyboard_type,error_rate,wpm,ror
0,30,0,US,qwerty,en,1-2,full,0.511945,61.9483,0.2288
1,27,0,MY,qwerty,en,7-8,laptop,0.871080,72.8871,0.3675
2,13,0,AU,qwerty,en,7-8,laptop,6.685633,24.1809,0.0667
3,21,0,IN,qwerty,en,3-4,full,2.130493,24.7112,0.0413
4,21,0,PH,qwerty,tl,7-8,laptop,1.893287,45.3364,0.2678
...,...,...,...,...,...,...,...,...,...,...
168589,20,0,US,qwerty,en,9-10,laptop,8.731466,24.9125,0.1842
168590,25,0,PL,qwerty,pl,9-10,laptop,0.000000,66.2946,0.0639
168591,38,1,US,qwerty,en,9-10,laptop,0.147929,75.6713,0.2021
168592,28,0,GB,qwerty,en,9-10,laptop,0.278552,91.7083,0.5133
168593,51,0,GB,qwerty,en,7-8,laptop,0.000000,56.8787,0.3409

In [23]:
for col in df.columns:
    print(col," --> ", df[col].nunique())

age  -->  118
course  -->  2
country  -->  233
layout  -->  4
native_language  -->  168
fingers  -->  6
keyboard_type  -->  4
error_rate  -->  24934
wpm  -->  149832
ror  -->  7701

In [28]:
# Exclude participants with high error
err_free_df = df[df['error_rate']<=3.0].copy()

# Exclude "10+" category if present
finger_df = err_free_df[err_free_df['fingers'] != '10+']

# Control for consistency by filtering to a specific subgroup
finger_df = finger_df[
    (finger_df['age']== 20) &
    (finger_df['layout'] == 'qwerty') &
    (finger_df['native_language'] == 'en') &
    (finger_df['keyboard_type'] == 'laptop') &
    (finger_df['course'] == 0)
]

# drop columns that now have only a single unique value
single_val_cols = [col for col in finger_df.columns if finger_df[col].nunique()<=1]
finger_df = finger_df.drop(columns= single_val_cols)

# compare typing speeds wpm across finger groups
finger_summary = finger_df.groupby('fingers')['wpm'].agg(['count','mean', 'median', 'std']).reset_index()
finger_summary

  fingers  count       mean   median        std
0     1-2    605  40.136691  38.2388  16.747138
1     3-4    391  45.089306  42.7370  17.672807
2     5-6    351  50.244505  48.5526  17.419402
3     7-8    440  54.223308  52.6148  18.947797
4    9-10   1044  59.323724  57.8523  20.416973

In [32]:
df_ror = err_free_df[
    (err_free_df['fingers'] =='9-10') &
    (err_free_df['age'] == 20) &
    (err_free_df['keyboard_type'] == 'laptop') &
    (err_free_df['layout'] == 'qwerty') &
    (err_free_df['native_language'] == 'en') &
    (err_free_df['course'] == 0) 
 ]

# filter low ROR <= 0.20) and high ROR (> 0.80)
low_ror = df_ror[df_ror['ror']<=0.20]['wpm']
high_ror = df_ror[df_ror['ror']>.80]['wpm']

# compare typing speeds between low and high ROR groups
ror_diff = pd.DataFrame({
    'group' : ['low ror <= 20%', 'high ror >= 80%'],
    'count' : [low_ror.count(), high_ror.count()],
    'mean_wpm' : [low_ror.mean(), high_ror.mean()],
    'median_wpm' : [low_ror.median(), high_ror.median()]
})

ror_diff

             group  count    mean_wpm  median_wpm
0   low ror <= 20%    271   42.360235     40.2122
1  high ror >= 80%      1  114.992900    114.9929

Influence of Typing Course

Compare typing speeds between participants with a typing course (HAS_TAKEN_TYPING_COURSE = 1) and without (HAS_TAKEN_TYPING_COURSE = 0), holding other variables such as KEYBOARD_TYPE, AGE range, and FINGER_COUNT constant.

In [34]:
# hold other variables constant (age = 20-25, laptop keyboard, 9-10 fingers, qwerty, english)
df_course = err_free_df[
    (err_free_df['age'].between(20, 25)) &
    (err_free_df['keyboard_type']== 'laptop' ) &
    (err_free_df['fingers'] == '9-10') &
    (err_free_df['layout'] == 'qwerty') &
    (err_free_df['native_language'] == 'en')
]

# compare typing speeds between course 1 (yes) and 0(no)
course_summary = df_course.groupby('course')['wpm'].agg(
Count = 'count',
Mean_wpm = 'mean',
median_wpm = 'median',
st_dev = 'std').reset_index()

# map numeric course flag to labels for clarity
course_summary['course'] = course_summary['course'].map({1: "course taken", 0:'not course taken'})
course_summary

             course  Count   Mean_wpm  median_wpm     st_dev
0  not course taken   5543  59.935250     59.6431  21.377785
1      course taken   3523  64.321653     64.1330  20.279773