# Emoji Sentiment

Are popular emojis generally associated with positive or negative sentiments?

The file `"emoji-sentiment.csv"` provides data on the sentiment associated with various emojis.

Researchers examined 1.6 million tweets across 13 European languages. Each tweet was labeled by annotators as positive (+1), negative (-1), or neutral (0). About 4% of these tweets included emojis.

Columns include:
- `Occurrences [5...max]`: Number of times the emoji appears in the dataset.
- `Position [0...1]`: Average position of the emoji in tweets, from start (0) to end (1).
- `Neg [0...1]`: Percentage of tweets with the emoji that are 'negative'.
- `Neu [0...1]`: Percentage of tweets with the emoji that are 'neutral'.
- `Pos [0...1]`: Percentage of tweets with the emoji that are 'positive'.

In [2]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'emoji-sentiment.csv'.

# from google.colab import files
# uploaded = files.upload()

In [4]:
import pandas as pd
df = pd.read_csv('emoji-sentiment.csv')
df

,Char,Image [twemoji],Unicode codepoint,Occurrences [5...max],Position [0...1],Neg [0...1],Neut [0...1],Pos [0...1],Sentiment bar (c.i. 95%),Unicode name,Unicode block
0,😂,😂,0x1f602,14622,0.805,0.247,0.285,0.468,NaN,FACE WITH TEARS OF JOY,Emoticons
1,❤,❤,0x2764,8050,0.747,0.044,0.166,0.790,NaN,HEAVY BLACK HEART,Dingbats
2,♥,♥,0x2665,7144,0.754,0.035,0.272,0.693,NaN,BLACK HEART SUIT,Miscellaneous Symbols
3,😍,😍,0x1f60d,6359,0.765,0.052,0.219,0.729,NaN,SMILING FACE WITH HEART-SHAPED EYES,Emoticons
4,😭,😭,0x1f62d,5526,0.803,0.436,0.220,0.343,NaN,LOUDLY CRYING FACE,Emoticons
...,...,...,...,...,...,...,...,...,...,...,...
746,♮,♮,0x266e,5,0.937,0.125,0.625,0.250,NaN,MUSIC NATURAL SIGN,Miscellaneous Symbols
747,🅾,🅾,0x1f17e,5,0.977,0.375,0.375,0.250,NaN,NEGATIVE SQUARED LATIN CAPITAL LETTER O,Enclosed Alphanumeric Supplement
748,🔄,🔄,0x1f504,5,0.971,0.125,0.750,0.125,NaN,ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCL...,Miscellaneous Symbols and Pictographs
749,☄,☄,0x2604,5,0.435,0.125,0.750,0.125,NaN,COMET,Miscellaneous Symbols
750,☨,☨,0x2628,5,0.458,0.125,0.750,0.125,NaN,CROSS OF LORRAINE,Miscellaneous Symbols

### Project Ideas:

Data Cleaning: 
- Remove unnecessary columns that are not useful for your analysis.

- Rename the remaining columns using `snake_case` (all lowercase letters with underscores between words).

New Variables:
- Add a new column called `sentiment`, where sentiment = (% positive tweets) - (% negative tweets).

- Add a `positive_flag` column that is `True` if `sentiment > 0` (or above a set threshold), otherwise `False`.

Types of questions you can now answer more easily:
- What percentage of emojis in the dataset have a positive sentiment?

- What percentage of the top 20 most popular emojis are positive?

- Which emoji (with more than 500 mentions) is the most positive?

- Which emoji (with more than 500 mentions) is the most negative?

- Where in the tweets are most emojis located (i.e. at the beginning or the end)?

- Is there a difference in the placement of positive versus negative emojis within a tweet?

In [12]:
df1 = df.drop(['Image [twemoji]', 'Sentiment bar (c.i. 95%)'], axis='columns')
df1.head()

,Char,Unicode codepoint,Occurrences [5...max],Position [0...1],Neg [0...1],Neut [0...1],Pos [0...1],Unicode name,Unicode block
0,😂,0x1f602,14622,0.805,0.247,0.285,0.468,FACE WITH TEARS OF JOY,Emoticons
1,❤,0x2764,8050,0.747,0.044,0.166,0.790,HEAVY BLACK HEART,Dingbats
2,♥,0x2665,7144,0.754,0.035,0.272,0.693,BLACK HEART SUIT,Miscellaneous Symbols
3,😍,0x1f60d,6359,0.765,0.052,0.219,0.729,SMILING FACE WITH HEART-SHAPED EYES,Emoticons
4,😭,0x1f62d,5526,0.803,0.436,0.220,0.343,LOUDLY CRYING FACE,Emoticons

In [5]:
# data cleaning -removing unnecessary columns
df.columns

Index(['Char', 'Image [twemoji]', 'Unicode codepoint', 'Occurrences [5...max]',
       'Position [0...1]', 'Neg [0...1]', 'Neut [0...1]', 'Pos [0...1]',
       'Sentiment bar (c.i. 95%)', 'Unicode name', 'Unicode block'],
      dtype='object')

In [16]:
# Rename the remaining columns using snake_case (all lowercase letters with underscores between words).
df1 = df1.rename(columns={
    'Char': 'char',
    'Unicode codepoint': 'unicode_codepoint',
    'Occurrences [5...max]': 'occurrences',
    'Position [0...1]' : 'position',
    'Neg [0...1]' : 'negative',
    'Neut [0...1]' : 'neutral',
    'Pos [0...1]' : 'positive',
    'Unicode name' : 'unicode_name',
    'Unicode block' : 'unicode_block'
})

df1.head()

,char,unicode_codepoint,occurrences,position,negative,neutral,positive,unicode_name,unicode_block
0,😂,0x1f602,14622,0.805,0.247,0.285,0.468,FACE WITH TEARS OF JOY,Emoticons
1,❤,0x2764,8050,0.747,0.044,0.166,0.790,HEAVY BLACK HEART,Dingbats
2,♥,0x2665,7144,0.754,0.035,0.272,0.693,BLACK HEART SUIT,Miscellaneous Symbols
3,😍,0x1f60d,6359,0.765,0.052,0.219,0.729,SMILING FACE WITH HEART-SHAPED EYES,Emoticons
4,😭,0x1f62d,5526,0.803,0.436,0.220,0.343,LOUDLY CRYING FACE,Emoticons

In [20]:
# Add a new column called sentiment, where sentiment = (% positive tweets) - (% negative tweets).

df1['sentiment'] = (df1['positive']-df1['negative'])
df1.head()

,char,unicode_codepoint,occurrences,position,negative,neutral,positive,unicode_name,unicode_block,sentiment,positive_flag
0,😂,0x1f602,14622,0.805,0.247,0.285,0.468,FACE WITH TEARS OF JOY,Emoticons,0.221,True
1,❤,0x2764,8050,0.747,0.044,0.166,0.790,HEAVY BLACK HEART,Dingbats,0.746,True
2,♥,0x2665,7144,0.754,0.035,0.272,0.693,BLACK HEART SUIT,Miscellaneous Symbols,0.658,True
3,😍,0x1f60d,6359,0.765,0.052,0.219,0.729,SMILING FACE WITH HEART-SHAPED EYES,Emoticons,0.677,True
4,😭,0x1f62d,5526,0.803,0.436,0.220,0.343,LOUDLY CRYING FACE,Emoticons,-0.093,False

In [21]:
# Add a positive_flag column that is True if sentiment > 0 (or above a set threshold), otherwise False.

df1['positive_flag'] = df1['sentiment']>0
df1.head()

,char,unicode_codepoint,occurrences,position,negative,neutral,positive,unicode_name,unicode_block,sentiment,positive_flag
0,😂,0x1f602,14622,0.805,0.247,0.285,0.468,FACE WITH TEARS OF JOY,Emoticons,0.221,True
1,❤,0x2764,8050,0.747,0.044,0.166,0.790,HEAVY BLACK HEART,Dingbats,0.746,True
2,♥,0x2665,7144,0.754,0.035,0.272,0.693,BLACK HEART SUIT,Miscellaneous Symbols,0.658,True
3,😍,0x1f60d,6359,0.765,0.052,0.219,0.729,SMILING FACE WITH HEART-SHAPED EYES,Emoticons,0.677,True
4,😭,0x1f62d,5526,0.803,0.436,0.220,0.343,LOUDLY CRYING FACE,Emoticons,-0.093,False

Types of questions you can now answer more easily:

What percentage of emojis in the dataset have a positive sentiment?

What percentage of the top 20 most popular emojis are positive?

Which emoji (with more than 500 mentions) is the most positive?

Which emoji (with more than 500 mentions) is the most negative?

Where in the tweets are most emojis located (i.e. at the beginning or the end)?

Is there a difference in the placement of positive versus negative emojis within a tweet?

In [34]:
# What percentage of emojis in the dataset have a positive sentiment?
pct_pos_overall = df1['positive_flag'].mean()*100
print(f"percentage of emojis in the dataset having a +ve sentiment - {pct_pos_overall:.2f}")

percentage of emojis in the dataset having a +ve sentiment - 82.42

In [ ]:
# What percentage of the top 20 most popular emojis are positive?
top_20_positive_pct = (
df1.sort_values(by='occurrences'))