# What is the First Day of the Week?

Whether the Gregorian calendar shows Sunday or Monday as the first day of the week depends on where you live.

Do more countries start the week on Sunday or Monday? What about people? What about by continent?

The file `first-day-of-week.csv` shows the first day of the week for each territory. The file `population.csv` shows the population in the year 2020 for each territory in millions, and the file `four-regions.csv` specifies whether each territory is in asia, europe, africa, or the americas.

In [1]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'first-day-of-week.csv', 'population.csv', and 'four-regions.csv'.

# from google.colab import files
# uploaded = files.upload()

In [39]:
import pandas as pd
df = pd.read_csv('first-day-of-week.csv')
df.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

In [2]:
pop = pd.read_csv('population.csv')
pop.head()

  alpha3  population
0    AFG       39.07
1    ALB        2.87
2    DZA       44.04
3    AND        0.08
4    AGO       33.45

In [3]:
regions = pd.read_csv('four-regions.csv')
regions.head()

  alpha3 four_regions
0    AUS         asia
1    BRN         asia
2    KHM         asia
3    CHN         asia
4    FJI         asia

### Project Ideas

- How many territories show Friday, Saturday, Sunday, and Monday as the `first_day` of the week?

- How many people start the week on Friday, Saturday, Sunday, and Monday?
	- Hint: This will involve a `merge`.

- Which of the `four_regions` predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?
	- Hint: This will also involve a `merge`.

In [40]:
# YOUR CODE HERE (add additional cells as needed)
df['first_day'].value_counts()

mon    186
sun     55
sat     15
fri      1
Name: first_day, dtype: int64

In [41]:
pop_merge_df = df.merge(pop, on='alpha3')
pop_merge_df

       territory alpha3 first_day   units      paper  population
0    Afghanistan    AFG       sat  metric         A4       39.07
1        Albania    ALB       mon  metric         A4        2.87
2        Algeria    DZA       sat  metric         A4       44.04
3        Andorra    AND       mon  metric         A4        0.08
4         Angola    AGO       mon  metric         A4       33.45
..           ...    ...       ...     ...        ...         ...
191    Venezuela    VEN       sun  metric  US-Letter       28.44
192      Vietnam    VNM       mon  metric         A4       98.08
193        Yemen    YEM       sun  metric         A4       36.13
194       Zambia    ZMB       mon  metric         A4       19.06
195     Zimbabwe    ZWE       sun  metric         A4       15.53

[196 rows x 6 columns]

In [42]:
# How many people start the week on Friday, Saturday, Sunday, and Monday?
pop_merge_df.groupby('first_day')['population'].sum()

first_day
fri       0.50
mon    3600.19
sat     431.79
sun    3844.08
Name: population, dtype: float64

In [43]:
df_rgn = df.merge(regions, on='alpha3')
df_rgn

       territory alpha3 first_day   units      paper four_regions
0    Afghanistan    AFG       sat  metric         A4         asia
1        Albania    ALB       mon  metric         A4       europe
2        Algeria    DZA       sat  metric         A4       africa
3        Andorra    AND       mon  metric         A4       europe
4         Angola    AGO       mon  metric         A4       africa
..           ...    ...       ...     ...        ...          ...
191    Venezuela    VEN       sun  metric  US-Letter     americas
192      Vietnam    VNM       mon  metric         A4         asia
193        Yemen    YEM       sun  metric         A4         asia
194       Zambia    ZMB       mon  metric         A4       africa
195     Zimbabwe    ZWE       sun  metric         A4       africa

[196 rows x 6 columns]

In [44]:
# Which of the four_regions predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?

# see how many territories in each region start on each day
pd.crosstab(df_rgn['four_regions'], df_rgn['first_day'])

first_day     fri  mon  sat  sun
four_regions
africa          0   43    5    6
americas        0   15    0   20
asia            1   27   10   21
europe          0   46    0    2


 - Europe and Africa predominantly start the week on Monday.
 - Asia and America divided between Sunday and monday